### ISSUE TITLE
Neurotree API

### ISSUE THREAD

**Issue by svdavid** [neuroelectro/neuroelectro_neurotree#1]
**Node search** Find people matching assorted search criteria (any or all of name, institution, research area). 

Example 1. Search for a person by name (searchname will be matched against first, middle and last names): 
http://neurotree.org/neurotree/jsonQuery.php?querytype=node&searchname=eccles

Example 1a. Quick alternative for name-only search (maybe faster than example 1?)
http://neurotree.org/neurotree/include/check_people.php?term=eccles

Example 2. Search for all people listed at an institution (searchinst will be matched against full or short-form institution names): 
http://neurotree.org/neurotree/jsonQuery.php?querytype=node&searchinst=ohsu

**Node info** Get node data for a unique person identified by their academic tree database id (pid). Data returned in same format as node search.

Example. Retrieve info for John Eccles (pid=114):
http://neurotree.org/neurotree/jsonQuery.php?querytype=node&pid=114

**Publication info** Get list of pid (indexing Neurotree people) with possible match to a given publication (identified by pmid):
http://neurotree.org/beta/include/check_pmid.php?term=7180315

**Connection info** Get all one-degree connections for a single node, specified by pid Returns a list of connected nodes with additional information about the connection (date, type of relationship, etc.). A single query returns only immediate (one-degree) connections, but subsequent queries to the returned pids allows tracing up or down the tree.

Example. Retrieve connections for John Eccles (pid=114): 
http://neurotree.org/neurotree/jsonQuery.php?querytype=connect&pid=114

**Comment by svdavid** [comment]
**Distance measurement** This one's a bit uglier but also more flexible.  Distance is returns in the variable _stepcount_.

Shortest path (backwards or forwards):
http://neurotree.org/neurotree/distance.php?pid1=77014&pid2=114&includera=1&includepd=1&includers=1&backonly=0&dispformat=json

Backwards only (through common ancestor):
http://neurotree.org/neurotree/distance.php?pid1=77014&pid2=4800&refresh=1&includera=1&includepd=1&includers=1&backonly=1&dispformat=json
(Quirk:  If the common ancestor path is the shortest path, then results will be returned as if backonly=0)

**Comment by stripathy** [comment]
thanks for putting together these APIs so quickly @svdavid ! They seem to all work as expected.

I put together a short ipython notebook for interacting with the API in python : https://github.com/neuroelectro/neuroelectro_neurotree/blob/master/neurotree_neuroelectro_comparison.ipynb

I have a question about what the **Publication info** service returns. In a couple cases that I tried, it seemed to work beautifully, where the entered PMID returned a single neurotree node ID which corresponded to the last author. 
http://neurotree.org/beta/include/check_pmid.php?term=23551921, for example returns a single neurotree node ID matching the last author.
`[{"pid":"4452","value":"0.6","label":"0.6"}]`

But this query, http://neurotree.org/beta/include/check_pmid.php?term=9185537 returns 3 neurotree nodes: 
`[{"pid":"1157","value":"0.08","label":"0.08"},{"pid":"4938","value":"0.04","label":"0.04"},{"pid":"21681","value":"0.01","label":"0.01"}]`
the last of which corresponds to the last author for this article. 

So my question is: what's the ordering of the authors returned from the query? Will the last node ID always be the last author of the publication? Also, I'm interpreting the returned 'value' as the predicted match between the neurotree ID and the pubmed author name, is this correct? In the few examples I manually checked, I haven't found any errors as far as I could tell.

**Comment by svdavid** [comment]
Ok, modified check_pmid as discussed.  Syntax for calling is the same, but it now returns a few extra bits of information:
_pid_:  neurotree person index
_value_:  score for match likelihood (1=high, 0=low.  I usually threshold at 0.3)
_label_: first init + last name.  Should confirm who you think pid corresponds to.
_authorlist_: "Last1 Inits1, Last2 Inits2, ... " for reference
_authorRank_: where label matches the author list, except last author is set to zero rather than N to make identification easy.  Sorry, probably horrible programming, but it seemed easier than making you count authors to determine if rank was last.

**Comment by stripathy** [comment]
@svdavid thanks! The `check_pmid` function now does what I want.

But can you double check that this query returns the desired result though? http://neurotree.org/beta/include/check_pmid.php?term=9185537 . It seems like the second returned element has the wrong authorRank and label.
`[{u'authorRank':` 3, u'authorList': u'Miller KK, Hoffer A, Svoboda KR, Lupica CR', u'pid': u'1157', u'value': u'0.08', u'label': u'KSVOBODA'}, {u'authorRank': 3, u'authorList': u'Miller KK, Hoffer A, Svoboda KR, Lupica CR', u'pid': u'4938', u'value': u'0.04', u'label': u'KSVOBODA'}, {u'authorRank': 0, u'authorList': u'Miller KK, Hoffer A, Svoboda KR, Lupica CR', u'pid': u'21681', u'value': u'0.01', u'label': u'CLUPICA'

**Comment by svdavid** [comment]
This is a disambiguation problem.  Kurt Svoboda and Karl Svoboda both match the label.  Neither has a very high score.  This looks like it should be a straightforward scopus author id match, but I've been limiting the number of queries per author because of the throttling problem, and a paper from 1997 is too far back.  It looks like I'm maxing out scopus queries for this week, so I'll have to wait to fix this one.  You can confirm author links by hand by logging in and clicking on the green check mark next to a given entry.

But generally, you want the pid with the highest score, and probably one above .3.  <.3 is uncertain, at least from neurotree's point of view.

**Comment by svdavid** [comment]
Note what happens, now that I've manually confirmed a match to Kurt Svoboda

http://neurotree.org/beta/include/check_pmid.php?term=9185537

**Comment by stripathy** [comment]
Looks good, thanks! I'm closing this issue, but @svdavid , you'll want to save the code at the top and post it somewhere when you're ready to formally release neurotree's API.

**Comment by stripathy** [comment]
@svdavid for this query, why is the authorRank of Buzsaki null instead of 0? is it cause of the unicode madness of Buzsaki's name?
http://neurotree.org/beta/include/check_pmid.php?term=11483306
`[{"pid":"5038","value":"1","label":"GBUZS\u00c1KI","authorList":"Henze DA, Buzs\u00e1ki G","authorRank":null},{"pid":"48643","value":"0.92","label":"DHENZE","authorList":"Henze DA, Buzs\u00e1ki G","authorRank":1}]`

http://www.ncbi.nlm.nih.gov/pubmed/11483306

**Comment by svdavid** [comment]
Yeah, the joys of character coding mismatches.  I changed to a shingle-based similarity test for author names.  That makes this example work, at least.

**Comment by stripathy** [comment]
thanks! closing again.
