### ISSUE TITLE
Getting Error 500 for neurotree path length search

### ISSUE THREAD

**Issue by rgerkin** [neuroelectro/neuroelectro_neurotree#12]
@svdavid A URL like [this](http://neurotree.org/beta/distance.php?pid1=77014&pid2=4800&refresh=1&includera=1&includepd=1&includers=1&backonly=1&dispformat=json&maxsteps=20) is giving me a server error (500) today.  It was working fine yesterday.

**Comment by svdavid** [comment]
Hmm. Running out of memory. Not sure why that just started happening.

Will look into it.

**Comment by svdavid** [comment]
@rgerkin: I see the problem. The tree is getting to big, and php has dumb memory management for arrays.  Got a hack in place that I think works.  Does it run for you now?

**Comment by rgerkin** [comment]
@svdavid It seems to work now.
