### ISSUE TITLE
neurotree distance functions choke when no path available

### ISSUE THREAD

**Issue by stripathy** [neuroelectro/neuroelectro_neurotree#5]
http://neurotree.org/neurotree/distance.php?pid1=458&pid2=2492&refresh=1&includera=1&includepd=1&includers=1&backonly=1&dispformat=json
matching between: Frances Jensen http://neurotree.org/neurotree/tree.php?pid=2492
and 
John Disterhoft http://neurotree.org/neurotree/tree.php?pid=458

I think I'd expect the API to return something like no match found in this case? Or alternatively, maybe I could be allowed to specify the maximum number of hops for the API to search. Whatever makes the problem more tractable on your end, @svdavid 

I'm noticing that I'm getting really long response times from the neurotree site when I'm making intractable path queries, so maybe we need to rethink if an API is a good approach vs a data dump.

**Comment by rgerkin** [comment]
Even 20 years ago on [The Oracle of Bacon](https://oracleofbacon.org/), it never choked on any connection, even when it took like 8 degrees to connect two actors; even then it responded in like a second.  Even at the time I think IMDB was larger than NeuroTree.  @svdavid Do you know if you're using the optimal path-finding algorithm for this?  Or maybe some paths could/should be cached to improve performance?

**Comment by stripathy** [comment]
I just want to reiterate that my problem with the current neurotree API is only when a path between two nodes doesn't exist (likely because of incompleteness of edges, but that's another issue). In these cases, neurotree should return to me a result like "no path found", in a sensible amount of time. I'm happy with the current API when a path exists, even if it takes a while to find it.

**Comment by svdavid** [comment]
Ok, you can specify the max number of steps now.  This should prevent some of the really slow queries.  

http://neurotree.org/beta/distance.php?pid1=458&pid2=2492&refresh=1&includera=1&includepd=1&includers=1&backonly=1&dispformat=json&maxsteps=10

It think it's a fairly optimal algorithm, just stepping out along every possible branch from each node until you meet.  I'm trying to minimize memory usage, which means that each step requires a database query.  I think the db table indices are fairly well optimized.  Might just be the load on the computer.  I'm running things a bit heavy in the background with an ongoing Proquest import, Pubmed refreshes, and a trickle of scopus imports.

**Comment by stripathy** [comment]
Thanks! the API now does what I expect
